server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search?createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

user-config:
  jsoup-connection-properties:
    user-agent: Mozilla/1.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
    referrer: http://www.google.com
  web-interface-path: /admin
  site-attributes:
    - url: https://dombulgakova.ru
      name: Дом Булгакова
    - url: https://et-cetera.ru/mobile/
      name: Театр ET CETERA
    - url: https://www.lutherancathedral.ru/
      name: Лютеранская Церковь



